# SPDX-License-Identifier: MIT
#
---
# The following file enables recreating a templated output dir by executing:
#   mk-scaffold clone "https://gitlab.com/cappysan/scaffolds/asustor-template" --input-file .answers.yml --output-dir output
answers:
  - include: "~/.config/scaffold/answers.yml"
    optional: True

  - author: "Julien Lecomte"
  - email: "julien@cappysan.dev"

  - project_name: "cappysan-pi-hole"
  - project_slug: "cappysan-pi-hole"
  - project_url: "https://gitlab.com/cappysan/asustor/pi-hole"
  - project_description: "Asustor Pi-Hole application."

  - has_documentation: False
  - documentation_url: ""

  - has_ci: True
  - has_pages: False
  - has_releases: True

  - has_precommit: True
  - has_precommit_codespell: True
  - has_precommit_nitpick: True

  - license: "MIT"
  - version: "2026.6.0-r62"
  - version_style: "semver-rev"
  - copyright_string: "Cappysan, Julien Lecomte, and contributors"

  - keep_placeholders: False

  - template_url: "https://gitlab.com/cappysan/scaffolds/asustor-template"
  - template_version: "1.1.0-r4"

  - creation_year: "2025"
  - last_update: "2026-06-13 10:40:47"

  - maintainer: "Cappysan"
  - developer: "Cappysan"

  - app_name: "pi-hole"
  - cfg_name: "pi-hole"
  - cappysan_name: "cappysan-pi-hole"
  - asustor_name: "asustor-pi-hole"

  - apk_description: "Asustor Certbot DNS application"
  - has_adm_desktop: True

  # Items without visible questions:
  - depends: '"python3(>=3.10.0)"'
  - adm_desktop_customizable: False
  - boot_priority_start: 50
  - boot_priority_stop: 30
  - has_upstream: False
