---
scrape_configs:
  - job_name: "pi-hole"
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: false
    file_sd_configs:
      - files:
          - "pi-hole.d/*.yml"
    relabel_configs: &instance_relabel
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+)(:[0-9]+)?"
        replacement: "${1}"
      - target_label: app
        replacement: pi-hole
