#!/usr/bin/env sh
# SPDX-License-Identifier: MIT
#
. /usr/local/AppCentral/cappysan-pi-hole/.env.install
cd ${APKG_PKG_DIR:-/nonexistent} || exit 1

if test -f "${APKG_PKG_DIR}/active"; then
  ./CONTROL/start-stop.sh reload
fi
