#!/usr/bin/env sh
# SPDX-License-Identifier: MIT
#
WHAT=pi-hole

function logger() {
  echo "${@}" >&2
  syslog --log 0 --level 0 --user SYSTEM --event "${@}"
}

. /usr/local/AppCentral/cappysan-pi-hole/.env.install
cd ${APKG_PKG_DIR:-/nonexistent} || exit 1

if test -f "${APKG_CFG_DIR}/active"; then
  ./CONTROL/start-stop.sh reload
fi
